[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && pip install -r requirements.txt && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
ENVIRONMENT = "production"
PORT = "8000"
PYTHONPATH = "backend"
